services:
  postgres:
    image: postgres:15-alpine
    container_name: task-scheduler-postgres
    environment:
      POSTGRES_DB: taskscheduler
      POSTGRES_USER: taskscheduler
      POSTGRES_PASSWORD: taskscheduler123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - task-scheduler-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskscheduler -d taskscheduler"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: task-scheduler-app
    env_file:
      - ../.env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - task-scheduler-network

volumes:
  postgres_data:

networks:
  task-scheduler-network:
    driver: bridge
